load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "sdk_proto",
    srcs = ["sdk.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//google/api:api_proto",
        "//grpc-gateway/protoc-gen-openapiv2/options:options_proto",
    ],
)

go_proto_library(
    name = "sdk_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "./sdk",
    proto = ":sdk_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//google/api:annotations_proto",
        "//grpc-gateway/protoc-gen-openapiv2/options:annotations_proto",
    ],
)
